pull_requests:
  do_not_increment_build_number: true

image: Visual Studio 2019
configuration: Release

install:
  - ps: dotnet tool install -g GitVersion.Tool

assembly_info:
  patch: false

before_build:
  - ps: nuget restore
  - ps: $NuGetVersion = & "dotnet gitversion /output json /showvariable NuGetVersion" 2>&1
  - ps: echo $NuGetVersion

build:
  verbosity: minimal
