pull_requests:
  do_not_increment_build_number: true

image: Visual Studio 2019
configuration: Release

install:
  - cmd: dotnet tool install -g GitVersion.Tool

assembly_info:
  patch: false

before_build:
  - nuget restore
  - ps: $NuGetVersion = (cmd /c dotnet gitversion /output json /showvariable NuGetVersion 2`>`&1)
  - ps: echo $NuGetVersion
  - cmd: echo %NuGetVersion%

build:
  verbosity: minimal
